name: auto-merge

on: pull_request

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    name: Merge pull request
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
