name: Auto approve and merge PRs by dependabot

on:
  pull_request_review:
    types:
      - submitted

jobs:
  automerge:
    name: Auto merge after successful checks
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.12.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: rebase
